name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Atur branch mana yang Anda inginkan untuk memicu analisis
  pull_request:
    branches:
      - main  # Atur branch mana yang Anda inginkan untuk memicu analisis

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK (untuk proyek Java, sesuaikan dengan kebutuhan bahasa pemrograman Anda)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      # Install SonarScanner
      - name: Install SonarScanner
        run: |
          wget https://github.com/SonarSource/sonar-scanner-cli/releases/download/4.6.2.2472/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner-cli-4.6.2.2472-linux.zip
          sudo mv sonar-scanner-4.6.2.2472-linux /opt/sonar-scanner
          export PATH=$PATH:/opt/sonar-scanner/bin

      # Run SonarQube analysis
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=UAS_DKP \
            -Dsonar.organization=your-org \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
